# Generated by Django 4.2.1 on 2023-06-01 04:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_rename_oder_order_rename_oderitem_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KhachHang',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='date_order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='oder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='snippingaddress',
            old_name='oder',
            new_name='order',
        ),
    ]
