# Generated by Django 4.2.1 on 2023-06-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_khachhang_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippingAddress',
            new_name='ShippingAddress',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantily',
            new_name='quantity',
        ),
    ]
